package:
  name: pyne
  version: 0.5.0rc1

source:
  fn: pyne-src.tar.gz
  #url : https://github.com/pyne/pyne/archive/0.5.0-rc1.tar.gz
  #url : https://github.com/scopatz/pyne/archive/unichr.tar.gz
  url : https://github.com/scopatz/pyne/archive/ci.tar.gz

requirements:
  build:
    - python
    - gcc  # [osx]
    - cmake
    - cython
    - moab
    - lapack
    - pytables
    - hdf5
    - numpy
    - scipy
  run:
    - python
    - moab
    - pytaps # [py2k]
    - hdf5
    - lapack
    - numpy
    - scipy
    - pytables

test:
  requires:
    - nose
    - jinja2
#  imports:
#    - pyne
#    - pyne._utils
#    - pyne.ace
#    - pyne.data
#    - pyne.enrichment
#    - pyne.jsoncpp
#    - pyne.material
#    - pyne.nucname
#    - pyne.pyne_config


about:
  home: http://pyne.io/
  license: BSD
