package:
  name: lasso
  version: 3.2

source:
  fn: lasso-3.2.tar.gz
  url: ftp://ftp.mcs.anl.gov/pub/fathom/lasso-3.2.tar.gz

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - cgm
    - moab
  run:
    - cgm
    - moab
  